services:
  db-mysql:
    image: mysql:5.7
    container_name: dock-db-mysql-port-4057
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    volumes:
    - mysqldata:/var/lib/mysql
    restart: always
    ports:
    - '4057:3306'
    environment:
      MYSQL_DATABASE: 'dbdock'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '196110'

volumes:
  mysqldata:
