version: '2'
services:
  db-postgres:
    image: postgres:latest
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
    - '4044:5432'
    environment:
    - POSTGRES_DB=dbdemo
    - POSTGRES_USER=tester
    - POSTGRES_PASSWORD=123

  app-pgadmin:
    image: dpage/pgadmin4
    ports:
    - 8001:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
    - db-postgres

volumes:
  pgdata:
  
