services:
  db-mysql:
    image: mysql:9.1
    container_name: dock-db-mysql-port-4091
    volumes:
    - mysql91data:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - '4091:3306'
    environment:
      MYSQL_DATABASE: 'dbdock'
      MYSQL_USER: 'tester'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '196110'

volumes:
  mysql91data:
